{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "0d83e0d7_b8886cb9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 7620
      },
      "writtenOn": "2021-08-31T17:48:08Z",
      "side": 1,
      "message": "Do we have a follow-up plan for adding a bot to test \"v8_use_external_startup_data \u003d false\" case so that such compilation error can be caught?\nMaybe we can add a TODO comment in this CL for such a task.",
      "revId": "1270301f3140280d73203665abe2d6bc9a5bd7fd",
      "serverId": "fca2d64a-0420-3532-b200-12848c95a47b"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "b1ebc3ff_7a7a6f92",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5495
      },
      "writtenOn": "2021-08-31T17:58:20Z",
      "side": 1,
      "message": "No, no plan for such a bot.  I\u0027m not sure where I\u0027d add such a comment. Instead, I\u0027ll file a bug.",
      "parentUuid": "0d83e0d7_b8886cb9",
      "revId": "1270301f3140280d73203665abe2d6bc9a5bd7fd",
      "serverId": "fca2d64a-0420-3532-b200-12848c95a47b"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "87158edf_bac53c8b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 5495
      },
      "writtenOn": "2021-08-31T18:00:52Z",
      "side": 1,
      "message": "https://crbug.com/pdfium/1716",
      "parentUuid": "b1ebc3ff_7a7a6f92",
      "revId": "1270301f3140280d73203665abe2d6bc9a5bd7fd",
      "serverId": "fca2d64a-0420-3532-b200-12848c95a47b"
    }
  ]
}