{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "896a5f1f_7054a434",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 3428039
      },
      "writtenOn": "2024-05-10T14:41:40Z",
      "side": 1,
      "message": "The reason for the CI failure is: \"Images differ: Also matches /b/s/w/ir/cache/builder/pdfium/testing/resources/pixel/bug_2106_expected.pdf.0.png\".\n\nI found that the files bug_2106_expected_skia.pdf.0.png and bug_2106_expected.pdf.0.png are binary identical. (bug_2106_expected_skia.pdf.0.png was downloaded from https://pdfium-gold.skia.org/img/images/6c78e8610171140de3efec65facca211.png)\n\nafter reading the code in run_pixel_tests.py, I found that when multiple file match the test file, the run_pixel_tests.py script will report a failure like ‘Images differ: Also matches ...’. if we only have a single file(for example if we delete bug_2106_expected.pdf.0.png), the test can be passed.",
      "revId": "ed735b455f448ba66c106664169d3464ca44df9b",
      "serverId": "fca2d64a-0420-3532-b200-12848c95a47b"
    }
  ]
}